"""Initial schema

Revision ID: 809e0fd791ae
Revises: 
Create Date: 2026-08-31 13:11:09.711026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809e0fd791ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('business_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('perishability', sa.String(length=20), nullable=False),
    sa.Column('storage_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("perishability IN ('HIGH', 'MEDIUM', 'LOW')", name='ck_categories_perishability'),
    sa.CheckConstraint("storage_type IN ('COLD', 'DRY', 'FROZEN')", name='ck_categories_storage_type'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('business_id', 'barcode', name='uq_inventory_business_barcode')
    )
    op.create_index('ix_inventory_business_category', 'inventory_items', ['business_id', 'category_id'], unique=False)
    op.create_index('ix_inventory_business_expiry', 'inventory_items', ['business_id', 'expiry_date'], unique=False)
    op.create_index('ix_inventory_business_id', 'inventory_items', ['business_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("transaction_type IN ('ADDED', 'UPDATED', 'SOLD', 'EXPIRED', 'DONATED')", name='ck_transaction_type_valid'),
    sa.CheckConstraint('quantity > 0', name='ck_transaction_quantity_positive'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_items.inventory_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_transactions')
    op.drop_index('ix_inventory_business_id', table_name='inventory_items')
    op.drop_index('ix_inventory_business_expiry', table_name='inventory_items')
    op.drop_index('ix_inventory_business_category', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('categories')
    op.drop_table('businesses')
    # ### end Alembic commands ###
